import { useEffect, useMemo, useState } from "react";
import AdminLayout from "@/components/AdminLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { UserPlus, Shield, Pencil, Search, Users, UserCheck, UserX } from "lucide-react";
import { getApiBaseUrl } from "@/lib/api";

type Employee = { id: number; full_name?: string; username: string; email: string; role: string; is_active: boolean; last_login?: string | null };
type Form = { fullName: string; username: string; email: string; role: string; password: string; is_active: boolean };
const emptyForm: Form = { fullName: "", username: "", email: "", role: "staff", password: "", is_active: true };
const apiUrl = getApiBaseUrl() || "http://localhost:5000";

const AdminManageEmployees = () => {
  const [employees, setEmployees] = useState<Employee[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Employee | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [saving, setSaving] = useState(false);
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token")}` };
  const load = async () => { try { setLoading(true); const response = await fetch(`${apiUrl}/api/employees`, { headers }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "โหลดข้อมูลไม่สำเร็จ"); setEmployees(Array.isArray(data) ? data : data.employees || []); } catch (e) { setError(e instanceof Error ? e.message : "ไม่สามารถโหลดข้อมูลได้"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => employees.filter(emp => { const q = search.toLowerCase().trim(); const matches = !q || [emp.full_name, emp.username, emp.email, emp.role].some(v => v?.toLowerCase().includes(q)); return matches && (status === "all" || (status === "active" ? emp.is_active : !emp.is_active)); }), [employees, search, status]);
  const active = employees.filter(e => e.is_active).length; const admins = employees.filter(e => e.role === "admin").length;
  const openAdd = () => { setEditing(null); setForm(emptyForm); setError(""); setOpen(true); };
  const openEdit = (employee: Employee) => { setEditing(employee); setForm({ fullName: employee.full_name || "", username: employee.username || "", email: employee.email || "", role: employee.role, password: "", is_active: employee.is_active }); setError(""); setOpen(true); };
  const save = async () => { if (!form.fullName.trim() || !form.username.trim() || !form.email.trim() || !form.role || (!editing && form.password.length < 6) || (form.password && form.password.length < 6)) { setError(editing ? "กรุณากรอกข้อมูลให้ครบถ้วน หรือใช้รหัสผ่านอย่างน้อย 6 ตัวอักษร" : "กรุณากรอกข้อมูลให้ครบถ้วนและรหัสผ่านอย่างน้อย 6 ตัวอักษร"); return; } try { setSaving(true); setError(""); const response = await fetch(editing ? `${apiUrl}/api/employees/${editing.id}` : `${apiUrl}/api/employees`, { method: editing ? "PUT" : "POST", headers, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "บันทึกไม่สำเร็จ"); setOpen(false); load(); } catch (e) { setError(e instanceof Error ? e.message : "ไม่สามารถบันทึกได้"); } finally { setSaving(false); } };
  const toggle = async (employee: Employee) => { if (!confirm(`${employee.is_active ? "ปิด" : "เปิด"}การใช้งานบัญชี ${employee.full_name || employee.username} หรือไม่?`)) return; const response = await fetch(`${apiUrl}/api/employees/${employee.id}/status`, { method: "PUT", headers, body: JSON.stringify({ is_active: !employee.is_active }) }); const data = await response.json(); if (!response.ok) { setError(data.message || "เปลี่ยนสถานะไม่สำเร็จ"); return; } load(); };
  const archive = async (employee: Employee) => { if (!confirm(`ระงับบัญชี ${employee.full_name || employee.username} หรือไม่?`)) return; const response = await fetch(`${apiUrl}/api/employees/${employee.id}`, { method: "DELETE", headers }); const data = await response.json(); if (!response.ok) { setError(data.message || "ระงับบัญชีไม่สำเร็จ"); return; } load(); };
  return <AdminLayout><div className="p-6 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-3"><Shield className="h-7 w-7 text-primary" /><h1 className="text-2xl font-bold">จัดการพนักงาน</h1></div><p className="mt-1 text-sm text-muted-foreground">จัดการบัญชีเจ้าหน้าที่และผู้ดูแลระบบ</p></div><Button onClick={openAdd}><UserPlus className="mr-2 h-4 w-4" />เพิ่มพนักงาน</Button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-4"><Users className="h-8 w-8 text-primary" /><div><p className="text-sm text-muted-foreground">พนักงานทั้งหมด</p><p className="text-2xl font-bold">{employees.length}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><UserCheck className="h-8 w-8 text-success" /><div><p className="text-sm text-muted-foreground">ใช้งานอยู่</p><p className="text-2xl font-bold">{active}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><Shield className="h-8 w-8 text-warning" /><div><p className="text-sm text-muted-foreground">ผู้ดูแลระบบ</p><p className="text-2xl font-bold">{admins}</p></div></CardContent></Card></div>
    <Card><CardHeader className="pb-3"><CardTitle className="text-base">รายชื่อพนักงาน</CardTitle><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="ค้นหาชื่อ username อีเมล หรือบทบาท" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full sm:w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ทุกสถานะ</SelectItem><SelectItem value="active">ใช้งานอยู่</SelectItem><SelectItem value="inactive">ปิดใช้งาน</SelectItem></SelectContent></Select></div></CardHeader><CardContent className="p-0">{error && <p className="m-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{loading ? <p className="py-12 text-center text-muted-foreground">กำลังโหลดข้อมูล...</p> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>ชื่อพนักงาน</TableHead><TableHead>Username</TableHead><TableHead>บทบาท</TableHead><TableHead>สถานะ</TableHead><TableHead>เข้าสู่ระบบล่าสุด</TableHead><TableHead className="text-right">จัดการ</TableHead></TableRow></TableHeader><TableBody>{filtered.length === 0 ? <TableRow><TableCell colSpan={6} className="py-12 text-center text-muted-foreground">ไม่พบข้อมูลพนักงาน</TableCell></TableRow> : filtered.map(emp => <TableRow key={emp.id} className={!emp.is_active ? "opacity-70" : ""}><TableCell><p className="font-semibold">{emp.full_name || "ไม่ระบุชื่อ"}</p><p className="text-xs text-muted-foreground">{emp.email}</p></TableCell><TableCell className="font-mono text-xs">{emp.username}</TableCell><TableCell><span className={`rounded-full px-2 py-1 text-xs font-medium ${emp.role === "admin" ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>{emp.role === "admin" ? "ผู้ดูแลระบบ" : "พนักงาน"}</span></TableCell><TableCell><span className={`inline-flex items-center gap-1 text-xs font-medium ${emp.is_active ? "text-success" : "text-warning"}`}>{emp.is_active ? <UserCheck className="h-3.5 w-3.5" /> : <UserX className="h-3.5 w-3.5" />}{emp.is_active ? "ใช้งานอยู่" : "ปิดใช้งาน"}</span></TableCell><TableCell>{emp.last_login ? new Date(emp.last_login).toLocaleString("th-TH") : "ยังไม่เคยเข้าใช้"}</TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" onClick={() => openEdit(emp)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="sm" className={emp.is_active ? "text-destructive" : "text-success"} onClick={() => toggle(emp)}>{emp.is_active ? <UserX className="h-4 w-4" /> : <UserCheck className="h-4 w-4" />}</Button><Button variant="ghost" size="sm" className="text-destructive" onClick={() => archive(emp)} title="ระงับบัญชี"><UserX className="h-4 w-4" /></Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? "แก้ไขพนักงาน" : "เพิ่มพนักงานใหม่"}</DialogTitle><DialogDescription>{editing ? "แก้ไขข้อมูลและสิทธิ์ของพนักงาน" : "สร้างบัญชีสำหรับพนักงานหรือผู้ดูแลระบบ"}</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>ชื่อ-นามสกุล</Label><Input className="mt-1" value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} /></div><div><Label>Username</Label><Input className="mt-1" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></div><div><Label>อีเมล</Label><Input type="email" className="mt-1" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></div><div><Label>บทบาท</Label><Select value={form.role} onValueChange={role => setForm({ ...form, role })}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="staff">พนักงาน</SelectItem><SelectItem value="admin">ผู้ดูแลระบบ</SelectItem></SelectContent></Select></div><div><Label>รหัสผ่าน {editing && <span className="text-xs text-muted-foreground">(เว้นว่างหากไม่เปลี่ยน)</span>}</Label><Input type="password" className="mt-1" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="อย่างน้อย 6 ตัวอักษร" /></div>{editing && <div><Label>สถานะบัญชี</Label><Select value={form.is_active ? "active" : "inactive"} onValueChange={value => setForm({ ...form, is_active: value === "active" })}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">ใช้งานอยู่</SelectItem><SelectItem value="inactive">ปิดใช้งาน</SelectItem></SelectContent></Select></div>}{error && <p className="text-sm text-destructive">{error}</p>}<Button className="w-full" onClick={save} disabled={saving}>{saving ? "กำลังบันทึก..." : "บันทึกข้อมูล"}</Button></div></DialogContent></Dialog>
  </div></AdminLayout>;
};
export default AdminManageEmployees;
