import { useEffect, useMemo, useState } from "react";
import AdminLayout from "@/components/AdminLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { UserPlus, Pencil, Key, Search, Users, UserCheck, UserX } from "lucide-react";
import { getApiBaseUrl } from "@/lib/api";

type Passenger = { id: number; full_name: string; username: string; email: string; gender: string; address: string; age: number; is_active: boolean };
type Form = { full_name: string; username: string; email: string; gender: string; address: string; age: string; password: string; is_active: boolean };
const emptyForm: Form = { full_name: "", username: "", email: "", gender: "", address: "", age: "", password: "", is_active: true };
const apiUrl = getApiBaseUrl() || "http://localhost:5000";

const PassengerManagement = () => {
  const [passengers, setPassengers] = useState<Passenger[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState("all"); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Passenger | null>(null); const [form, setForm] = useState<Form>(emptyForm); const [saving, setSaving] = useState(false);
  const headers = { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token")}` };
  const load = async () => { try { setLoading(true); const response = await fetch(`${apiUrl}/api/passengers`, { headers }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "โหลดข้อมูลไม่สำเร็จ"); setPassengers(Array.isArray(data) ? data : []); } catch (e) { setError(e instanceof Error ? e.message : "ไม่สามารถโหลดข้อมูลได้"); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = useMemo(() => passengers.filter(p => { const q = search.toLowerCase().trim(); const matches = !q || [p.full_name, p.username, p.email].some(v => v?.toLowerCase().includes(q)); return matches && (status === "all" || (status === "active" ? p.is_active : !p.is_active)); }), [passengers, search, status]);
  const active = passengers.filter(p => p.is_active).length;
  const openAdd = () => { setEditing(null); setForm(emptyForm); setError(""); setOpen(true); };
  const openEdit = (p: Passenger) => { setEditing(p); setForm({ full_name: p.full_name || "", username: p.username || "", email: p.email || "", gender: p.gender || "", address: p.address || "", age: String(p.age || ""), password: "", is_active: p.is_active }); setError(""); setOpen(true); };
  const save = async () => { if (!form.full_name.trim() || !form.username.trim() || !form.email.trim() || !form.gender || !form.address.trim() || Number(form.age) <= 0 || (!editing && form.password.length < 6)) { setError(editing ? "กรุณากรอกข้อมูลให้ครบถ้วน" : "กรุณากรอกข้อมูลให้ครบถ้วนและรหัสผ่านอย่างน้อย 6 ตัวอักษร"); return; } try { setSaving(true); setError(""); const response = await fetch(editing ? `${apiUrl}/api/passengers/${editing.id}` : `${apiUrl}/api/passengers`, { method: editing ? "PUT" : "POST", headers, body: JSON.stringify({ ...form, age: Number(form.age) }) }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "บันทึกไม่สำเร็จ"); setOpen(false); load(); } catch (e) { setError(e instanceof Error ? e.message : "ไม่สามารถบันทึกได้"); } finally { setSaving(false); } };
  const toggle = async (p: Passenger) => { if (!confirm(`${p.is_active ? "ปิด" : "เปิด"}การใช้งานบัญชี ${p.full_name} หรือไม่?`)) return; const response = await fetch(`${apiUrl}/api/passengers/${p.id}/status`, { method: "PUT", headers, body: JSON.stringify({ is_active: !p.is_active }) }); const data = await response.json(); if (!response.ok) { setError(data.message || "เปลี่ยนสถานะไม่สำเร็จ"); return; } load(); };
  const resetPassword = async (p: Passenger) => { if (!confirm(`รีเซ็ตรหัสผ่านของ ${p.full_name} เป็น 123456 หรือไม่?`)) return; const response = await fetch(`${apiUrl}/api/passengers/${p.id}/reset-password`, { method: "PUT", headers }); const data = await response.json(); if (!response.ok) { setError(data.message || "รีเซ็ตรหัสผ่านไม่สำเร็จ"); return; } alert(data.message); };
  return <AdminLayout><div className="p-6 space-y-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-3"><Users className="h-7 w-7 text-primary" /><h1 className="text-2xl font-bold">จัดการผู้โดยสาร</h1></div><p className="mt-1 text-sm text-muted-foreground">ดูแลข้อมูลและสถานะบัญชีผู้โดยสาร</p></div><Button onClick={openAdd}><UserPlus className="mr-2 h-4 w-4" />เพิ่มผู้โดยสาร</Button></div>
    <div className="grid gap-4 sm:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-4"><Users className="h-8 w-8 text-primary" /><div><p className="text-sm text-muted-foreground">ทั้งหมด</p><p className="text-2xl font-bold">{passengers.length}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><UserCheck className="h-8 w-8 text-success" /><div><p className="text-sm text-muted-foreground">ใช้งานอยู่</p><p className="text-2xl font-bold">{active}</p></div></CardContent></Card><Card><CardContent className="flex items-center gap-3 p-4"><UserX className="h-8 w-8 text-muted-foreground" /><div><p className="text-sm text-muted-foreground">ปิดใช้งาน</p><p className="text-2xl font-bold">{passengers.length - active}</p></div></CardContent></Card></div>
    <Card><CardHeader className="pb-3"><CardTitle className="text-base">รายชื่อผู้โดยสาร</CardTitle><div className="flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="ค้นหาชื่อ ชื่อผู้ใช้ หรืออีเมล" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full sm:w-44"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">ทุกสถานะ</SelectItem><SelectItem value="active">ใช้งานอยู่</SelectItem><SelectItem value="inactive">ปิดใช้งาน</SelectItem></SelectContent></Select></div></CardHeader><CardContent className="p-0">{error && <p className="m-4 rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}{loading ? <p className="py-12 text-center text-muted-foreground">กำลังโหลดข้อมูล...</p> : <div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>ชื่อผู้โดยสาร</TableHead><TableHead>ชื่อผู้ใช้</TableHead><TableHead>อีเมล</TableHead><TableHead>เพศ / อายุ</TableHead><TableHead>สถานะ</TableHead><TableHead className="text-right">จัดการ</TableHead></TableRow></TableHeader><TableBody>{filtered.length === 0 ? <TableRow><TableCell colSpan={6} className="py-12 text-center text-muted-foreground">ไม่พบข้อมูลผู้โดยสาร</TableCell></TableRow> : filtered.map(p => <TableRow key={p.id}><TableCell className="font-semibold">{p.full_name}</TableCell><TableCell>{p.username}</TableCell><TableCell>{p.email}</TableCell><TableCell>{p.gender || "-"} / {p.age || "-"} ปี</TableCell><TableCell><span className={`rounded-full px-2 py-1 text-xs font-medium ${p.is_active ? "bg-success/10 text-success" : "bg-destructive/10 text-destructive"}`}>{p.is_active ? "ใช้งานอยู่" : "ปิดใช้งาน"}</span></TableCell><TableCell className="text-right"><Button variant="ghost" size="sm" onClick={() => openEdit(p)} title="แก้ไข"><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="sm" onClick={() => resetPassword(p)} title="รีเซ็ตรหัสผ่าน"><Key className="h-4 w-4" /></Button><Button variant="ghost" size="sm" className={p.is_active ? "text-destructive" : "text-success"} onClick={() => toggle(p)} title={p.is_active ? "ปิดใช้งาน" : "เปิดใช้งาน"}>{p.is_active ? <UserX className="h-4 w-4" /> : <UserCheck className="h-4 w-4" />}</Button></TableCell></TableRow>)}</TableBody></Table></div>}</CardContent></Card>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-lg"><DialogHeader><DialogTitle>{editing ? "แก้ไขผู้โดยสาร" : "เพิ่มผู้โดยสารใหม่"}</DialogTitle><DialogDescription>{editing ? "แก้ไขข้อมูลบัญชีผู้โดยสาร" : "กรอกข้อมูลเพื่อสร้างบัญชีผู้โดยสาร"}</DialogDescription></DialogHeader><div className="grid gap-4"><div><Label>ชื่อ-นามสกุล</Label><Input className="mt-1" value={form.full_name} onChange={e => setForm({ ...form, full_name: e.target.value })} /></div><div className="grid grid-cols-2 gap-3"><div><Label>ชื่อผู้ใช้</Label><Input className="mt-1" value={form.username} onChange={e => setForm({ ...form, username: e.target.value })} /></div><div><Label>อายุ</Label><Input type="number" min="1" className="mt-1" value={form.age} onChange={e => setForm({ ...form, age: e.target.value })} /></div></div><div><Label>อีเมล</Label><Input type="email" className="mt-1" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></div><div><Label>เพศ</Label><Select value={form.gender} onValueChange={gender => setForm({ ...form, gender })}><SelectTrigger className="mt-1"><SelectValue placeholder="เลือกเพศ" /></SelectTrigger><SelectContent><SelectItem value="male">ชาย</SelectItem><SelectItem value="female">หญิง</SelectItem><SelectItem value="other">อื่น ๆ</SelectItem></SelectContent></Select></div><div><Label>ที่อยู่</Label><Input className="mt-1" value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} /></div>{!editing && <div><Label>รหัสผ่าน</Label><Input type="password" className="mt-1" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder="อย่างน้อย 6 ตัวอักษร" /></div>}{error && <p className="text-sm text-destructive">{error}</p>}<Button onClick={save} disabled={saving}>{saving ? "กำลังบันทึก..." : "บันทึกข้อมูล"}</Button></div></DialogContent></Dialog>
  </div></AdminLayout>;
};
export default PassengerManagement;
